services:
  # The FastAPI server handling the WebSockets and UI requests
  - type: web
    name: nodedrive-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # The Simulator Physics Engine pushing telemetry to the FastAPI server
  - type: worker
    name: nodedrive-simulator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simulator.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WS_URL
        fromService:
          type: web
          name: nodedrive-api
          envVarKey: RENDER_EXTERNAL_URL
        # This dynamically tells the Simulator to connect to the Web API url
