// ============================================================
// SHARED TYPES & INTERFACES FOR NODEDRIVE v3
// ============================================================
// This file centralizes all Typescript interfaces validating data 
// moving between the FastAPI Python backend and the Vite DOM frontend.

// -----------------------------
// Vehicle Telemetry
// -----------------------------
export interface Vehicle {
    vehicle_id: string;
    lat: number;
    lng: number;
    heading: number;      // 0 to 360 degree bearing used for movement orientation
    speed: number;        // km/h
    type: string;         // 'car' | 'emergency' 

    // Server-computed safety flags
    risk?: boolean;          // Collision risk boolean
    hazard_alert?: boolean;  // Proximity to hazard cluster boolean
    yield_alert?: boolean;   // Proximity to active emergency unit boundary boolean
}

// -----------------------------
// Hazard & Threat Data
// -----------------------------
export interface HazardCluster {
    id: string;           // Autogenerated cluster ID
    lat: number;          // Evaluated median center of cluster
    lng: number;          // Evaluated median center of cluster
    count: number;        // Number of discrete user reports in this 20m zone
    type: string;
}

// -----------------------------
// Websocket Transfer Envelope
// -----------------------------
// This is the shape of the master JSON payload dispatched by 
// the server on the /ws/view socket every 1 second.
export interface BackendPayload {
    vehicles: Record<string, Vehicle>; // Dictionary mapped by vehicle_id
    hazards: HazardCluster[];          // Array of clustered threat coordinates
}
